### ISSUE TITLE
Add importer from Authenticator Pro

### ISSUE THREAD

**Issue by FineFindus** [twofas/2fas-android#20]
Please add support for importing from [Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro), a popular 2-FA application. It provides backups as an encrypted JSON file, the encryption and decryption code can be found [here](https://github.com/jamie-mh/AuthenticatorPro/blob/master/AuthenticatorPro.Core/src/Backup/Encryption/StrongBackupEncryption.cs#L83).

I tried to port the code myself, but due to various problems in #18 I couldn't get the app to compile/run.

**Comment by 2fas-com** [comment]
We related the request to the dev team. We'll keep you posted!

**Comment by FineFindus** [comment]
Great, as mentioned, I would also try to implement it myself, but I'm unable to get the app to run.

**Comment by 2fas-com** [comment]
Why is that?

**Comment by FineFindus** [comment]
It's an error with the FirebaseInitialisation (see #18), after getting confused by the setup and then seeing this error, I decided to give up for now and focus on another project.

<details>
<summary>Logs</summary>


```
 java.lang.RuntimeException: Unable to create application com.twofasapp.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.twofasapp.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.twofasapp.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:186)
                                                                                                    	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:183)
                                                                                                    	at com.twofasapp.App.onCreate(App.kt:124)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

</details>

**Comment by Ashvith10** [comment]
@2fas-com I also have the same issue.

```console
2023-10-20 16:12:07.160  8205-8205  AndroidRuntime          com.twofasapp.debug                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.twofasapp.debug, PID: 8205
                                                                                                    java.lang.RuntimeException: Unable to create application com.twofasapp.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.twofasapp.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.twofasapp.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                                                                    	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:207)
                                                                                                    	at com.twofasapp.App.onCreate(App.kt:65)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

I've followed  the page you've linked carefully. It is outdated, and needs to be improved.

**Comment by 2fas-com** [comment]
Import option has been added to the Android and iOS systems.
