### ISSUE TITLE
Android app crash at launch

### ISSUE THREAD

**Issue by Lauryy06** [twofas/2fas-android#81]
Since the update (5.0.0) the app won't open anymore. Below is the crash stack. I'm running on LineageOS 20 on a Poco F1?

```
2023-10-30 11:51:33.683  8815-8815  AndroidRuntime          pid-8815                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.twofasapp, PID: 8815
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlcipher.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SourceFile:7)
                                                                                                    	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:7)
                                                                                                    	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:3)
                                                                                                    	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:1)
                                                                                                    	at com.twofasapp.App.onCreate(SourceFile:108)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	```

**Comment by Tipoff4317** [comment]
This is a data point.  Just updated to 5.0.0 on Android 13, and it's working as expected.

**Comment by Lauryy06** [comment]
After investigation, it was a bug with my Android package installer, I reinstalled the application in a different way and it works perfectly again. Sorry for the inconvenience 😅.
